M48
; DRILL file {KiCad 7.0.7} date Thu Sep  7 20:52:32 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-09-07T20:52:32+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X22.555Y47.97
X27.405Y47.97
X55.575Y47.97
X60.425Y47.97
T2
X22.255Y51.0
X27.705Y51.0
X55.275Y51.0
X60.725Y51.0
T3
X4.0Y50.0
X4.0Y4.0
X126.0Y50.0
X126.0Y4.0
T0
M30
