M48
; DRILL file {KiCad (6.0.8)} date Sun Oct  2 10:43:29 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-10-02T10:43:29+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.8)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.200
%
G90
G05
T1
X91.555Y-61.03
X96.405Y-61.03
X124.575Y-61.03
X129.425Y-61.03
T2
X91.255Y-58.0
X96.705Y-58.0
X124.275Y-58.0
X129.725Y-58.0
T3
X73.0Y-59.0
X73.0Y-105.0
X195.0Y-59.0
X195.0Y-105.0
T0
M30
